from app.models.domain import (  # noqa: F401
    AgentActionProposal,
    AgentConversationContext,
    AgentEpisode,
    Attachment,
    AuditLog,
    BomItem,
    BuildPlan,
    BuildPlanItem,
    Category,
    ComponentRelation,
    ComponentRelationEvidenceLink,
    EngineeringDocument,
    EngineeringDocumentBlock,
    EngineeringDocumentPage,
    EvidenceAnchor,
    IdempotencyRecord,
    InventoryLot,
    Loan,
    Location,
    LocationMapBinding,
    Material,
    PickAllocation,
    PickTask,
    PickTaskItem,
    Product,
    ProductBomAlternate,
    ProductBomAlternateEvidenceLink,
    ProductBomItem,
    ProductRevision,
    Project,
    ProjectReservation,
    PurchaseOrder,
    Role,
    Session,
    StockMovement,
    Stocktake,
    Supplier,
    User,
    WarehouseMap,
    WarehouseMapEdge,
    WarehouseMapNode,
)
from app.spatial.models import DynamicOverlay, SemanticZone, SpatialAsset, SpatialDock  # noqa: F401
from app.spatial.orm_geometry import register_legacy_geometry_hooks

register_legacy_geometry_hooks()
