export interface SlotGeometry { x_norm: number; y_norm: number; width_norm: number; height_norm: number }
export interface TwinSlot { name: string; location_id: number | null; descendant_ids: number[]; geometry: SlotGeometry; material_kind_count: number; materials: { name: string; quantity: string; unit: string }[]; quantities_by_unit: Record<string,string> }
export interface TwinAsset { code: string; name: string; style: string; location_id: number; x_m:number; y_m:number; facing:string; dimensions:{width:number;height:number;depth:number}; footprint:{width_m:number;depth_m:number}; pick_node_code:string; full_path:string; zone:string; slots:TwinSlot[]; material_kind_count:number; quantities_by_unit:Record<string,string>; storage_boxes:{level:number;code:string;name:string;location_id?:number}[] }
export interface TwinNode { code:string;node_type:string;x_m:number;y_m:number;label:string }
export interface TwinEdge { code:string;from_node:string;to_node:string;distance_m:number;enabled:boolean;bidirectional:boolean }
export interface TwinRoute { graph_hash?:string;strategy:string;total_distance_m:number;ordered_stop_nodes:string[];segments:{from_node:string;to_node:string;path_nodes:string[];distance_m:number}[] }
export interface TwinAllocation {id:number;location_id:number;route_node_code:string;material_name:string;material_code:string;full_path:string;remaining_quantity:string;status:string}
export interface TwinTask {id:number;pick_task_no:string;status:string;warehouse_map_id:number|null;warehouse_graph_hash:string;route_plan:TwinRoute;allocations:TwinAllocation[];next_stop:TwinAllocation|null}
export interface TwinSnapshot {schema_version:number;map:{id?:number;code:string;name:string;version:string;graph_hash:string;width_m:number;height_m:number;nodes:TwinNode[];edges:TwinEdge[]};assets:TwinAsset[];route:TwinRoute|null;task:TwinTask|null;closed_edge_codes?:string[];decorations:{kind:string;x_m:number;y_m:number}[];preview_slots?:Record<string,string>;metadata:Record<string,unknown>}
export interface TwinController {select(code:string,slot?:string|null,focus?:boolean):void;setMode(mode:'2d'|'3d'):Promise<void>;updateStop(index:number,focus?:boolean):void;stats():Record<string,unknown>;dispose():void}
export interface TwinOptions {initialMode?:'2d'|'3d';focusLocationId?:number|null;closureActive?:boolean;onToggleClosure?:()=>void;onRefresh?:()=>void;onOpenLocation?:(id:number|null)=>void;onOpenTask?:(id:number|null)=>void;loadRenderer?:()=>Promise<unknown>}
