<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api } from '../api/client'
type Mode='categories'|'locations'|'suppliers'
interface Row {id:number;code:string;name:string;parent_id?:number|null;sort_order?:number;type?:string;full_path?:string;manager?:string;contact?:string;phone?:string;email?:string;lead_time_days?:number;is_active:boolean}
const props=defineProps<{mode:Mode}>();const rows=ref<Row[]>([]);const dialog=ref(false);const editing=ref<number|null>(null)
const form=reactive({code:'',name:'',parent_id:null as number|null,sort_order:0,type:'bin',manager:'',notes:'',contact:'',phone:'',email:'',lead_time_days:0,is_active:true})
const title=computed(()=>({categories:'物料分类',locations:'存放库位',suppliers:'供应商'}[props.mode]));const endpoint=computed(()=>`/${props.mode}`)
async function load(){rows.value=(await api.get<Row[]>(endpoint.value)).data}
function open(row?:Row){Object.assign(form,{code:'',name:'',parent_id:null,sort_order:0,type:'bin',manager:'',notes:'',contact:'',phone:'',email:'',lead_time_days:0,is_active:true},row||{});editing.value=row?.id||null;dialog.value=true}
async function save(){if(editing.value)await api.put(`${endpoint.value}/${editing.value}`,form);else await api.post(endpoint.value,form);ElMessage.success('已保存');dialog.value=false;load()}
async function remove(row:Row){await ElMessageBox.confirm(`确认删除“${row.name}”？`,'危险操作',{type:'warning'});await api.delete(`${endpoint.value}/${row.id}`);load()}
onMounted(load);watch(()=>props.mode,load)
</script>
<template><div class="page"><div class="page-header"><div><h1 class="page-title">{{title}}</h1><div class="page-subtitle">{{mode==='locations'?'按仓库、柜、层、抽屉、格子维护完整位置路径':mode==='categories'?'维护电子元件分类树，已使用分类不可删除':'维护采购联系信息和默认交期'}}</div></div><el-button type="primary" @click="open()">新增{{title}}</el-button></div><el-card class="card"><el-table :data="rows" row-key="id" stripe><el-table-column prop="code" label="编码" width="150"/><el-table-column prop="name" label="名称" min-width="180"/><el-table-column v-if="mode==='locations'" prop="full_path" label="完整路径" min-width="260"/><el-table-column v-if="mode==='locations'" prop="type" label="类型" width="110"/><el-table-column v-if="mode==='suppliers'" prop="contact" label="联系人"/><el-table-column v-if="mode==='suppliers'" prop="phone" label="电话"/><el-table-column v-if="mode==='suppliers'" prop="email" label="邮箱" min-width="180"/><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.is_active?'success':'info'">{{row.is_active?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="140"><template #default="{row}"><el-button link type="primary" @click="open(row)">编辑</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table></el-card><el-dialog v-model="dialog" :title="`${editing?'编辑':'新增'}${title}`" width="520px"><el-form label-position="top"><div class="two"><el-form-item label="编码" required><el-input v-model="form.code"/></el-form-item><el-form-item label="名称" required><el-input v-model="form.name"/></el-form-item></div><el-form-item v-if="mode!=='suppliers'" label="父节点"><el-select v-model="form.parent_id" clearable filterable><el-option v-for="x in rows.filter(x=>x.id!==editing)" :key="x.id" :label="x.full_path||x.name" :value="x.id"/></el-select></el-form-item><el-form-item v-if="mode==='locations'" label="库位类型"><el-select v-model="form.type"><el-option v-for="x in ['warehouse','area','cabinet','shelf','drawer','bin','temporary','scrap']" :key="x" :label="x" :value="x"/></el-select></el-form-item><template v-if="mode==='suppliers'"><div class="two"><el-form-item label="联系人"><el-input v-model="form.contact"/></el-form-item><el-form-item label="电话"><el-input v-model="form.phone"/></el-form-item></div><el-form-item label="邮箱"><el-input v-model="form.email"/></el-form-item><el-form-item label="交期（天）"><el-input-number v-model="form.lead_time_days" :min="0"/></el-form-item></template><el-switch v-model="form.is_active" active-text="启用" inactive-text="停用"/></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :disabled="!form.code||!form.name" @click="save">保存</el-button></template></el-dialog></div></template>
<style scoped>.two{display:grid;grid-template-columns:1fr 1fr;gap:14px}:deep(.el-select){width:100%}</style>
