<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { api } from '../api/client'
import type { Page } from '../types'
import { formatQuantity, formatSignedQuantity } from '../utils/format'
interface Movement {id:number;movement_no:string;material_id:number;operation_type:string;quantity_delta:string;before_quantity:string;after_quantity:string;before_reserved:string;after_reserved:string;operator_id:number;reason:string;request_id:string;created_at:string}
const data=ref<Page<Movement>>({items:[],total:0,page:1,page_size:20});const filter=reactive({q:'',operation_type:'',page:1,page_size:20})
const labels:Record<string,string>={initial:'初始库存',inbound:'入库',outbound:'出库',scrap:'报废',refund:'退料',reserve:'预留',cancel_reservation:'取消预留',reservation_to_outbound:'预留转出库',adjust:'盘点修正',transfer:'库位转移',reverse:'冲正'}
async function load(){data.value=(await api.get<Page<Movement>>('/stock-movements',{params:filter})).data}onMounted(load)
async function download(){const response=await api.get<Blob>('/exports/stock-movements',{responseType:'blob'});const anchor=window.document.createElement('a');anchor.href=window.URL.createObjectURL(response.data);anchor.download='stock_movements.csv';anchor.click();window.URL.revokeObjectURL(anchor.href)}
</script>
<template><div class="page"><div class="page-header"><div><h1 class="page-title">库存流水</h1><div class="page-subtitle">历史记录不可修改或删除，错误通过关联冲正流水纠正</div></div><el-button @click="download">导出 CSV</el-button></div><el-card class="card"><div class="toolbar"><el-input v-model="filter.q" placeholder="流水号" clearable style="width:230px"/><el-select v-model="filter.operation_type" placeholder="全部类型" clearable style="width:180px"><el-option v-for="(v,k) in labels" :key="k" :label="v" :value="k"/></el-select><el-button @click="load">筛选</el-button></div><el-table :data="data.items" height="calc(100vh - 280px)" stripe><el-table-column prop="movement_no" label="流水号" width="205" fixed/><el-table-column label="类型" width="130"><template #default="{row}"><el-tag effect="plain">{{labels[row.operation_type]||row.operation_type}}</el-tag></template></el-table-column><el-table-column prop="material_id" label="物料 ID" width="90"/><el-table-column label="数量变化" width="110" align="right"><template #default="{row}"><b :class="Number(row.quantity_delta)>=0?'success-number':'danger-number'">{{formatSignedQuantity(row.quantity_delta)}}</b></template></el-table-column><el-table-column label="库存前 → 后" width="150"><template #default="{row}">{{formatQuantity(row.before_quantity)}} → {{formatQuantity(row.after_quantity)}}</template></el-table-column><el-table-column label="预留前 → 后" width="150"><template #default="{row}">{{formatQuantity(row.before_reserved)}} → {{formatQuantity(row.after_reserved)}}</template></el-table-column><el-table-column prop="reason" label="业务原因" min-width="180" show-overflow-tooltip/><el-table-column prop="operator_id" label="操作人 ID" width="100"/><el-table-column prop="created_at" label="时间" width="185"/></el-table><el-pagination v-model:current-page="filter.page" v-model:page-size="filter.page_size" :total="data.total" layout="total,sizes,prev,pager,next" class="pager" @change="load"/></el-card></div></template>
<style scoped>.pager{justify-content:flex-end;margin-top:16px}</style>
